name: Deploy Food Menu App to Kubernetes

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build and push Docker image
      run: |
        docker build -t your-docker-hub-username/food-menu:latest .
        docker push your-docker-hub-username/food-menu:latest

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v4
      with:
        manifests: |
          ./deployment.yaml
          ./service.yaml
        images: |
          your-docker-hub-username/food-menu:latest
        kubectl-version: 'latest'
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
